Improving performance for onMarkerClick event (Android only)
react-native-maps/react-native-maps pull request #4782
Opened 2023-07-03 08:05 UTC by MartinaMuscarella

### Does any other open PR do the same thing?
No

(please answer here)

### What issue is this PR fixing?

Some issue that could be get improvements form this is #4776 

### How did you test this PR?

We have an app that needs to load several thousands of marker. On Android devices the onPress event is very slow to be triggered. We discovered that it was caused by the iteration on the markers. We used the setTag(Object)/getTag() to make it faster and avoid the search on markers.

2023-11-06 09:10 UTC, MartinaMuscarella commented
Still relevant

2023-12-08 13:17 UTC, salah-ghanim requested changes
Using Marker.setTag is extremely memory efficient.

let's avoid using views to keep track of IDs, let's keep track of IDs directly instead (markerId, viewId)

2023-12-08 13:17 UTC, salah-ghanim commented on android/src/main/java/com/rnmaps/maps/MapMarker.java
> +    marker.setTag(this);
@MartinaMuscarella this code is way too heavy compared to the functionality we're trying to achieve here 

specifically, you're storing a full view collection as an "attachment" to each Marker, and according to google docs:
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker#setTag(java.lang.Object)
there is no automated mechanism by google to free memory here

if you look at setOnMarkerClickListener inside MapView.java you can see that only the markerIdentifier is needed.

and if you look at almost all the calls for getMarkerMap in MapView.java you find out only the viewID is needed to dispatch the event through MapManager.receiveEvent

2023-12-08 13:17 UTC, salah-ghanim commented on android/src/main/java/com/rnmaps/maps/MapView.java
> +    MapMarker airMarker = (MapMarker) marker.getTag();
@MartinaMuscarella I would suggest creating a lightweight class in Android and call it MarkerTag
in it you can simply add two properties: viewId, markerId

then you can attach it to the marker as a tag

and where ever in the MapView getMarkerMap is called, replace it with a call to get the tagFirst as you did, and have a new manager.pushEvent function that takes the viewID directly, not just the viewObject

2024-01-26 02:33 UTC, cctv1005s commented
@MartinaMuscarella  Hi, could you please take a look at the comments? This PR is very important for Android users.

2024-05-10 01:47 UTC, closed without merging

2024-07-11 17:24 UTC, WeidsonWikaro commented
Still relevant